### ISSUE TITLE
Error: name 'FakeUserAgentError' is not defined

### ISSUE THREAD

**Issue by despecial** [vinaywadhwa/justwatch-alfred#9]
Using Alfred 5, the workflow doesnt seem to work.
Locale is set to DE

**Comment by vinaywadhwa** [comment]
@despecial Thanks for reporting. Fixed in [1.1.2](https://github.com/vinaywadhwa/justwatch-alfred/releases/tag/1.1.2) .

**Comment by conformist1** [comment]
Just updated to 1.1.2 and error is still persistent — any ideas? I'm also not seeing where to edit the country code.
